### ISSUE TITLE
Installation error on Windows 11

### ISSUE THREAD

**Issue by sadjadeb** [Rayan25062011/SkyScratch#2]
It seems that pip cannot install this package on Windows 11 because of an error in the setup.py file.
pip version: 22.3

Here is the output of the command:

![image](https://user-images.githubusercontent.com/47966506/199505383-cfaa8d0f-d852-4678-9f18-ed907f784c3b.png)

**Comment by Rayan25062011** [comment]
Should be fixed now, try again.

**Comment by Rayan25062011** [comment]
Yes, im looking to fix this problem, try the new instructions while its getting fixed.
